"""model_fixes — autogenerated + cleaned

Migration changes:
1. categories.name: nullable → NOT NULL
2. category_subscriptions: add unique constraint uq_category_subscriber
3. category_subscriptions: FK ondelete CASCADE + nullable
4. custom_fields: add post_type_id, content_id columns + FK
5. pages.content: VARCHAR(255) → Text

Revision ID: 1e3b270d84f4
Revises: b15b018b8e3d
Create Date: 2026-06-15 15:27:16.877704
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e3b270d84f4'
down_revision: Union[str, None] = 'b15b018b8e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### 1. categories: name NOT NULL ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### 2. category_subscriptions: unique constraint + FK CASCADE + nullable ###
    with op.batch_alter_table('category_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('subscriber',
               existing_type=sa.BigInteger(),
               nullable=True)
        batch_op.create_unique_constraint('uq_category_subscriber', ['category', 'subscriber'])
        batch_op.create_foreign_key('fk_cs_category', 'categories',
                                    ['category'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_cs_subscriber', 'users',
                                    ['subscriber'], ['id'], ondelete='CASCADE')

    # ### 3. pages: content VARCHAR(255) → Text ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### 4. custom_fields: add post_type_id, content_id ###
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('content_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('fk_cf_post_type', 'custom_post_types',
                                    ['post_type_id'], ['id'])


def downgrade() -> None:
    # ### 4. custom_fields: revert ###
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cf_post_type', type_='foreignkey')
        batch_op.drop_column('content_id')
        batch_op.drop_column('post_type_id')

    # ### 3. pages: content Text → VARCHAR(255) ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### 2. category_subscriptions: revert ###
    with op.batch_alter_table('category_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cs_subscriber', type_='foreignkey')
        batch_op.drop_constraint('fk_cs_category', type_='foreignkey')
        batch_op.drop_constraint('uq_category_subscriber', type_='unique')
        batch_op.alter_column('subscriber',
               existing_type=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.BigInteger(),
               nullable=False)

    # ### 1. categories: name revert to nullable ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
