"""aiconfig

Revision ID: 364c1bfbb714
Revises: 1e3b270d84f4
Create Date: 2026-07-04 23:50:30.947382

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '364c1bfbb714'
down_revision: Union[str, Sequence[str], None] = '1e3b270d84f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False, comment='配置名称'),
                    sa.Column('api_url', sa.String(length=500), nullable=False, comment='API 端点 URL'),
                    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='加密后的 API Key'),
                    sa.Column('model', sa.String(length=100), nullable=False, comment='模型名称'),
                    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供商'),
                    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
                    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'name', name='uq_ai_config_user_name'),
                    comment='用户 AI 配置表'
                    )
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_configs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('category_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_subscriptions_subscriber_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('category_subscriptions_category_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('category_subscriptions_category_fkey'), 'categories', ['category'],
                                    ['id'])
        batch_op.create_foreign_key(batch_op.f('category_subscriptions_subscriber_fkey'), 'users', ['subscriber'],
                                    ['id'])

    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_configs_user_id'))

    op.drop_table('ai_configs')
    # ### end Alembic commands ###
