"""add published_at_to_article_and_user_name_level_to_audit_log

Revision ID: c3ab8756dfe5
Revises: cd6395fc2579
Create Date: 2026-06-13 19:11:55.171066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ab8756dfe5'
down_revision: Union[str, Sequence[str], None] = 'cd6395fc2579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_media_hash'))
        batch_op.create_index('idx_media_hash', ['hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('idx_media_hash')
        batch_op.create_index(batch_op.f('idx_media_hash'), ['hash'], unique=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('level')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
