"""initial_squash 鈥?consolidate all model changes

Combines AIConfig migration + model_fixes + AdminSettings/deleted_at/JSON/EncryptedField.

Revision ID: d36e5c7f1180
Revises: b15b018b8e3d
Create Date: 2026-07-14 11:12:09.510063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36e5c7f1180'
down_revision: Union[str, Sequence[str], None] = 'b15b018b8e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('settings_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.create_index('idx_admin_settings_user', ['user'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('tags_list',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_articles_published_at'))
        batch_op.create_index('idx_articles_published_at', ['published_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=shared.utils.crypto.EncryptedField(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=shared.utils.crypto.EncryptedField(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('idx_articles_published_at')
        batch_op.create_index(batch_op.f('idx_articles_published_at'), ['created_at'], unique=False)
        batch_op.alter_column('tags_list',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_settings_user')

    op.drop_table('admin_settings')
    # ### end Alembic commands ###
