endpoints: [ ]
models: { }
generation:
  django_ninja:
    output_dir: apps/generated
    router_file: generated_router.py
    models_file: auto_orm.py
  fastapi:
    output_dir: src/api/v1/generated
    router_file: generated_router.py
  typescript:
    output_dir: frontend-next/types/generated
    types_file: api-types.ts
    client_file: api-client.ts
