"""
Models 包 - 懒加载版本

所有模型类通过 __getattr__ 按需导入，避免启动时一次性加载所有模型文件。
Base 保持立即导入（SQLAlchemy 元数据初始化必需）。

由代码生成器自动生成 - 请勿手动修改
"""

from sqlalchemy.orm import declarative_base

Base = declarative_base()

# ==================== 懒加载映射表 ====================
# 模型名 -> 相对模块路径（不含 shared.models 前缀）
_LAZY_IMPORTS = {
    'AIWorkflow': '.ai.ai_workflow',
    'Ad': '.ad.ad',
    'AdClick': '.ad.ad_click',
    'AdImpression': '.ad.ad_impression',
    'AdPlacement': '.ad.ad_placement',
    'ApprovalRecord': '.collaboration.approval_record',
    'ApprovalStep': '.collaboration.approval_step',
    'Article': '.article.article',
    'ArticleAnnotation': '.article.article_annotation',
    'ArticleContent': '.article.article_content',
    'ArticleLike': '.article.article_like',
    'ArticleRevision': '.article.article_revision',
    'ArticleRevisionNote': '.article.article_revision_note',
    'ArticleSEO': '.article.article_seo',
    'AuditLog': '.system.audit_log',
    'BaiduAnalyticsConfig': '.analytics.baidu_analytics_config',
    'BlockPattern': '.widget.block_pattern',
    'Capability': '.rbac.capability',
    'Cart': '.ecommerce.cart',
    'CartItem': '.ecommerce.cart_item',
    'Category': '.category.category',
    'CategorySubscription': '.category.category_subscription',
    'ChatGroup': '.chat.chat_group',
    'ChatGroupInvite': '.chat.chat_group_invite',
    'ChatGroupMember': '.chat.chat_group_member',
    'Comment': '.comment.comment',
    'CommentSubscription': '.comment.comment_subscription',
    'CommentVote': '.comment.comment_vote',
    'ContentMapping': '.multisite.content_mapping',
    'CryptoPayment': '.payment.crypto_payment',
    'CustomField': '.content.custom_field',
    'CustomPostType': '.content.custom_post_type',
    'DataRetentionPolicy': '.enterprise.data_retention_policy',
    'DeploymentLog': '.enterprise.deployment_log',
    'DeploymentScript': '.enterprise.deployment_script',
    'DownloadTask': '.media.download_task',
    'EmailServiceConfig': '.integration.email_service_config',
    'EmailSubscription': '.notification.email_subscription',
    'EnterpriseLicense': '.enterprise.enterprise_license',
    'FieldPermission': '.security.field_permission',
    'FileHash': '.media.file_hash',
    'Form': '.form.form',
    'FormField': '.form.form_field',
    'FormSubmission': '.form.form_submission',
    'GlobalStyle': '.theme.global_style',
    'GlobalStyleConfig': '.theme.global_style_config',
    'GoogleAnalyticsConfig': '.analytics.google_analytics_config',
    'LDAPConfig': '.integration.ldap_config',
    'LoginAttempt': '.security.login_attempt',
    'Media': '.media.media',
    'MediaFolder': '.media.media_folder',
    'MediaOptimization': '.media.media_optimization',
    'MenuItems': '.menu.menu_items',
    'MenuLocation': '.menu.menu_location',
    'MenuLocationAssignment': '.menu.menu_location_assignment',
    'Menus': '.menu.menus',
    'MigrationLog': '.migration.migration_log',
    'MigrationTask': '.migration.migration_task',
    'MonitoringAlert': '.monitoring.monitoring_alert',
    'MonitoringMetric': '.monitoring.monitoring_metric',
    'Notification': '.notification.notification',
    'NotificationIntegration': '.integration.notification_integration',
    'OAuthAccount': '.user.o_auth_account',
    'Order': '.ecommerce.order',
    'OrderItem': '.ecommerce.order_item',
    'PageBuilder': '.page.page_builder',
    'PageView': '.analytics.page_view',
    'Pages': '.page.pages',
    'PaymentGateway': '.payment.payment_gateway',
    'PaymentTransaction': '.payment.payment_transaction',
    'PayoutRequest': '.revenue.payout_request',
    'PermissionAuditLog': '.rbac.permission_audit_log',
    'Plugin': '.plugin.plugin',
    'PrivateMessage': '.chat.private_message',
    'Product': '.ecommerce.product',
    'ReportHistory': '.report.report_history',
    'RevenueRecord': '.revenue.revenue_record',
    'RevenueSharingConfig': '.revenue.revenue_sharing_config',
    'Role': '.rbac.role',
    'RoleCapability': '.rbac.role_capability',
    'SAMLConfig': '.integration.saml_config',
    'SLAReport': '.monitoring.sla_report',
    'SSOProvider': '.integration.sso_provider',
    'ScheduledReport': '.report.scheduled_report',
    'SearchHistory': '.search.search_history',
    'SearchIndex': '.search.search_index',
    'SensitiveWord': '.security.sensitive_word',
    'ShareStat': '.social.share_stat',
    'Site': '.multisite.site',
    'SiteUser': '.multisite.site_user',
    'SupportTicket': '.enterprise.support_ticket',
    'SupportTicketReply': '.enterprise.support_ticket_reply',
    'SystemSettings': '.system.system_settings',
    'Task': '.collaboration.task',
    'TaxConfig': '.payment.tax_config',
    'Theme': '.theme.theme',
    'TokenBlacklist': '.security.token_blacklist',
    'UploadChunk': '.media.upload_chunk',
    'UploadTask': '.media.upload_task',
    'User': '.user.user',
    'UserActivity': '.analytics.user_activity',
    'UserBlock': '.user.user_block',
    'UserRevenueStats': '.revenue.user_revenue_stats',
    'UserRole': '.rbac.user_role',
    'UserSession': '.user.user_session',
    'VIPFeature': '.vip.vip_feature',
    'VIPPlan': '.vip.vip_plan',
    'VIPSubscription': '.vip.vip_subscription',
    'Webhook': '.webhook.webhook',
    'WebhookDelivery': '.webhook.webhook_delivery',
    'WidgetInstance': '.widget.widget_instance',
    'Workspace': '.collaboration.workspace',
    'WorkspaceMember': '.collaboration.workspace_member',
}

# 已加载的模型缓存（避免重复导入）
_loaded_models = {}


def __getattr__(name):
    """模块级 __getattr__：按需懒加载模型类"""
    if name in _loaded_models:
        return _loaded_models[name]

    module_path = _LAZY_IMPORTS.get(name)
    if module_path is not None:
        import importlib
        module = importlib.import_module(module_path, package='shared.models')
        cls = getattr(module, name)
        # 缓存到模块命名空间，后续访问直接命中
        globals()[name] = cls
        _loaded_models[name] = cls
        return cls

    raise AttributeError(f"module 'shared.models' has no attribute {name!r}")


# ==================== 自动生成 - __all__ ====================
# 此部分由脚本自动生成 - 请勿手动修改

__all__ = [
    'AIWorkflow',
    'Ad',
    'AdClick',
    'AdImpression',
    'AdPlacement',
    'ApprovalRecord',
    'ApprovalStep',
    'Article',
    'ArticleAnnotation',
    'ArticleContent',
    'ArticleLike',
    'ArticleRevision',
    'ArticleRevisionNote',
    'ArticleSEO',
    'AuditLog',
    'BaiduAnalyticsConfig',
    'Base',
    'BlockPattern',
    'Capability',
    'Cart',
    'CartItem',
    'Category',
    'CategorySubscription',
    'ChatGroup',
    'ChatGroupInvite',
    'ChatGroupMember',
    'Comment',
    'CommentSubscription',
    'CommentVote',
    'ContentMapping',
    'CryptoPayment',
    'CustomField',
    'CustomPostType',
    'DataRetentionPolicy',
    'DeploymentLog',
    'DeploymentScript',
    'DownloadTask',
    'EmailServiceConfig',
    'EmailSubscription',
    'EnterpriseLicense',
    'FieldPermission',
    'FileHash',
    'Form',
    'FormField',
    'FormSubmission',
    'GlobalStyle',
    'GlobalStyleConfig',
    'GoogleAnalyticsConfig',
    'LDAPConfig',
    'LoginAttempt',
    'Media',
    'MediaFolder',
    'MediaOptimization',
    'MenuItems',
    'MenuLocation',
    'MenuLocationAssignment',
    'Menus',
    'MigrationLog',
    'MigrationTask',
    'MonitoringAlert',
    'MonitoringMetric',
    'Notification',
    'NotificationIntegration',
    'OAuthAccount',
    'Order',
    'OrderItem',
    'PageBuilder',
    'PageView',
    'Pages',
    'PaymentGateway',
    'PaymentTransaction',
    'PayoutRequest',
    'PermissionAuditLog',
    'Plugin',
    'PrivateMessage',
    'Product',
    'ReportHistory',
    'RevenueRecord',
    'RevenueSharingConfig',
    'Role',
    'RoleCapability',
    'SAMLConfig',
    'SLAReport',
    'SSOProvider',
    'ScheduledReport',
    'SearchHistory',
    'SearchIndex',
    'SensitiveWord',
    'ShareStat',
    'Site',
    'SiteUser',
    'SupportTicket',
    'SupportTicketReply',
    'SystemSettings',
    'Task',
    'TaxConfig',
    'Theme',
    'TokenBlacklist',
    'UploadChunk',
    'UploadTask',
    'User',
    'UserActivity',
    'UserBlock',
    'UserRevenueStats',
    'UserRole',
    'UserSession',
    'VIPFeature',
    'VIPPlan',
    'VIPSubscription',
    'Webhook',
    'WebhookDelivery',
    'WidgetInstance',
    'Workspace',
    'WorkspaceMember',
]
# ============================================================================
