"""
Models 包 - 懒加载版本

所有模型类通过 __getattr__ 按需导入，避免启动时一次性加载 90+ 个模型文件。
Base 保持立即导入（SQLAlchemy 元数据初始化必需）。
"""

from sqlalchemy.orm import declarative_base

Base = declarative_base()

# ==================== 懒加载映射表 ====================
# 模型名 -> 相对模块路径（不含 shared.models 前缀）
_LAZY_IMPORTS = {
    'AuditLog': '.audit_log',
    'AIWorkflow': '.ai_workflow',
    'PageBuilder': '.page_builder',
    'GlobalStyle': '.global_style',
    'FieldPermission': '.field_permission',
    'User': '.user',
    'Article': '.article',
    'Category': '.category',
    'CategorySubscription': '.category_subscription',
    'Media': '.media',
    'MediaFolder': '.media_folder',
    'MediaOptimization': '.media_optimization',
    'ArticleRevisionNote': '.article_revision_note',
    'SystemSettings': '.system_settings',
    'ArticleContent': '.article_content',
    'ArticleLike': '.article_like',
    'FileHash': '.file_hash',
    'Menus': '.menus',
    'MenuItems': '.menu_items',
    'MenuLocation': '.menu_location',
    'MenuLocationAssignment': '.menu_location_assignment',
    'Pages': '.pages',
    'UploadTask': '.upload_task',
    'UploadChunk': '.upload_chunk',
    'DownloadTask': '.download_task',
    'Notification': '.notification',
    'PrivateMessage': '.private_message',
    'UserBlock': '.user_block',
    'SearchHistory': '.search_history',
    'SearchIndex': '.search_index',
    'PageView': '.page_view',
    'UserActivity': '.user_activity',
    'VIPPlan': '.vip_plan',
    'VIPSubscription': '.vip_subscription',
    'VIPFeature': '.vip_feature',
    'CustomField': '.custom_field',
    'EmailSubscription': '.email_subscription',
    'ArticleRevision': '.article_revision',
    'Plugin': '.plugin',
    'Theme': '.theme',
    'Form': '.form',
    'FormField': '.form_field',
    'FormSubmission': '.form_submission',
    'WidgetInstance': '.widget_instance',
    'BlockPattern': '.block_pattern',
    'CustomPostType': '.custom_post_type',
    'CommentVote': '.comment_vote',
    'CommentSubscription': '.comment_subscription',
    'Comment': '.comment',
    'OAuthAccount': '.o_auth_account',
    'ArticleSEO': '.article_seo',
    'ShareStat': '.share_stat',
    'Product': '.product',
    'Cart': '.cart',
    'CartItem': '.cart_item',
    'Order': '.order',
    'SensitiveWord': '.sensitive_word',
    'UserSession': '.user_session',
    'LoginAttempt': '.login_attempt',
    'TokenBlacklist': '.token_blacklist',
    'AdPlacement': '.ad_placement',
    'Ad': '.ad',
    'AdClick': '.ad_click',
    'AdImpression': '.ad_impression',
    'RevenueRecord': '.revenue_record',
    'RevenueSharingConfig': '.revenue_sharing_config',
    'PayoutRequest': '.payout_request',
    'UserRevenueStats': '.user_revenue_stats',
    'ChatGroup': '.chat_group',
    'ChatGroupMember': '.chat_group_member',
    'ChatGroupInvite': '.chat_group_invite',
    'ScheduledReport': '.scheduled_report',
    'ReportHistory': '.report_history',
    'ArticleAnnotation': '.article_annotation',
    'Webhook': '.webhook',
    'WebhookDelivery': '.webhook_delivery',
    'Role': '.role',
    'Capability': '.capability',
    'RoleCapability': '.role_capability',
    'UserRole': '.user_role',
    'PermissionAuditLog': '.permission_audit_log',
    'Workspace': '.workspace',
    'WorkspaceMember': '.workspace_member',
    'Task': '.task',
    'ApprovalRecord': '.approval_record',
    'ApprovalStep': '.approval_step',
    'Site': '.site',
    'SiteUser': '.site_user',
    'ContentMapping': '.content_mapping',
    'GoogleAnalyticsConfig': '.google_analytics_config',
    'BaiduAnalyticsConfig': '.baidu_analytics_config',
    'NotificationIntegration': '.notification_integration',
    'EmailServiceConfig': '.email_service_config',
    'SAMLConfig': '.saml_config',
    'LDAPConfig': '.ldap_config',
    'SSOProvider': '.sso_provider',
    'PaymentGateway': '.payment_gateway',
    'PaymentTransaction': '.payment_transaction',
    'CryptoPayment': '.crypto_payment',
    'TaxConfig': '.tax_config',
    'OrderItem': '.order_item',
    'EnterpriseLicense': '.enterprise_license',
    'SupportTicket': '.support_ticket',
    'SupportTicketReply': '.support_ticket_reply',
    'DeploymentScript': '.deployment_script',
    'DeploymentLog': '.deployment_log',
    'MonitoringAlert': '.monitoring_alert',
    'MonitoringMetric': '.monitoring_metric',
    'MigrationTask': '.migration_task',
    'MigrationLog': '.migration_log',
    'GlobalStyleConfig': '.global_style_config',
}

# 已加载的模型缓存（避免重复导入）
_loaded_models = {}


def __getattr__(name):
    """模块级 __getattr__：按需懒加载模型类"""
    if name in _loaded_models:
        return _loaded_models[name]

    module_path = _LAZY_IMPORTS.get(name)
    if module_path is not None:
        import importlib
        module = importlib.import_module(module_path, package='shared.models')
        cls = getattr(module, name)
        # 缓存到模块命名空间，后续访问直接命中
        globals()[name] = cls
        _loaded_models[name] = cls
        return cls

    raise AttributeError(f"module 'shared.models' has no attribute {name!r}")


__all__ = [
    'Base',
    'AuditLog',
    'AIWorkflow',
    'PageBuilder',
    'GlobalStyle',
    'FieldPermission',
    'User',
    'Article',
    'Category',
    'CategorySubscription',
    'Media',
    'MediaFolder',
    'MediaOptimization',
    'ArticleRevisionNote',
    'SystemSettings',
    'ArticleContent',
    'ArticleLike',
    'FileHash',
    'Menus',
    'MenuItems',
    'MenuLocation',
    'MenuLocationAssignment',
    'Pages',
    'UploadTask',
    'UploadChunk',
    'DownloadTask',
    'Notification',
    'PrivateMessage',
    'UserBlock',
    'SearchHistory',
    'SearchIndex',
    'PageView',
    'UserActivity',
    'VIPPlan',
    'VIPSubscription',
    'VIPFeature',
    'CustomField',
    'EmailSubscription',
    'ArticleRevision',
    'Plugin',
    'Theme',
    'Form',
    'FormField',
    'FormSubmission',
    'WidgetInstance',
    'BlockPattern',
    'CustomPostType',
    'CommentVote',
    'CommentSubscription',
    'Comment',
    'OAuthAccount',
    'ArticleSEO',
    'ShareStat',
    'Product',
    'Cart',
    'CartItem',
    'Order',
    'SensitiveWord',
    'UserSession',
    'LoginAttempt',
    'TokenBlacklist',
    'AdPlacement',
    'Ad',
    'AdClick',
    'AdImpression',
    'RevenueRecord',
    'RevenueSharingConfig',
    'PayoutRequest',
    'UserRevenueStats',
    'ChatGroup',
    'ChatGroupMember',
    'ChatGroupInvite',
    'ScheduledReport',
    'ReportHistory',
    'ArticleAnnotation',
    'Webhook',
    'WebhookDelivery',
    'Role',
    'Capability',
    'RoleCapability',
    'UserRole',
    'PermissionAuditLog',
    'Workspace',
    'WorkspaceMember',
    'Task',
    'ApprovalRecord',
    'ApprovalStep',
    'Site',
    'SiteUser',
    'ContentMapping',
    'GoogleAnalyticsConfig',
    'BaiduAnalyticsConfig',
    'NotificationIntegration',
    'EmailServiceConfig',
    'SAMLConfig',
    'LDAPConfig',
    'SSOProvider',
    'PaymentGateway',
    'PaymentTransaction',
    'CryptoPayment',
    'TaxConfig',
    'OrderItem',
    'EnterpriseLicense',
    'SupportTicket',
    'SupportTicketReply',
    'DeploymentScript',
    'DeploymentLog',
    'MonitoringAlert',
    'MonitoringMetric',
    'MigrationTask',
    'MigrationLog',
    'GlobalStyleConfig'
]
# ============================================================================
