apiVersion: v1
kind: ConfigMap
metadata:
  name: { { include "fastblog.fullname" . } }-config
  labels:
    {{- include "fastblog.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: "5432"
  DB_NAME: "{{ .Values.postgresql.auth.database }}"
  DB_USER: "{{ .Values.postgresql.auth.username }}"
  DB_PASSWORD: "{{ .Values.postgresql.auth.postgresPassword }}"
  
  REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379/0"
  
  MEILISEARCH_URL: "http://{{ .Release.Name }}-meilisearch:7700"
  MEILISEARCH_KEY: "{{ .Values.meilisearch.masterKey }}"
  
  HOST: "0.0.0.0"
  PORT: "9421"
  DEBUG: "{{ .Values.config.debug }}"
  SECRET_KEY: "{{ .Values.config.secretKey }}"
  
  BACKUP_DIR: "/app/backups"
  TRANSLATIONS_DIR: "/app/translations"
  
  { { - if .Values.config.oauth.googleClientId } }
  GOOGLE_OAUTH_CLIENT_ID: "{{ .Values.config.oauth.googleClientId }}"
  GOOGLE_OAUTH_CLIENT_SECRET: "{{ .Values.config.oauth.googleClientSecret }}"
  { { - end } }
  
  { { - if .Values.config.oauth.githubClientId } }
  GITHUB_OAUTH_CLIENT_ID: "{{ .Values.config.oauth.githubClientId }}"
  GITHUB_OAUTH_CLIENT_SECRET: "{{ .Values.config.oauth.githubClientSecret }}"
  { { - end } }
  
  { { - if .Values.config.ldap.server } }
  LDAP_SERVER: "{{ .Values.config.ldap.server }}"
  LDAP_PORT: "{{ .Values.config.ldap.port }}"
  LDAP_BASE_DN: "{{ .Values.config.ldap.baseDN }}"
  LDAP_BIND_DN: "{{ .Values.config.ldap.bindDN }}"
  LDAP_BIND_PASSWORD: "{{ .Values.config.ldap.bindPassword }}"
  { { - end } }
