apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "fastblog.fullname" . } }-media
  labels:
    {{- include "fastblog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "fastblog.fullname" . } }-storage
  labels:
    {{- include "fastblog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "fastblog.fullname" . } }-backups
  labels:
    {{- include "fastblog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "fastblog.fullname" . } }-logs
  labels:
    {{- include "fastblog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
