// Cloudflare Worker - Auto-generated by FastBlog
// Generated at: 2026-05-02T09:21:29.037358

const ROUTES_CONFIG = [];

addEventListener('fetch', event => {
    event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
    const url = new URL(request.url);
    const pathname = url.pathname;

    // 查找匹配的路由
    const matchedRoute = ROUTES_CONFIG.find(route => {
        if (route.route === pathname) return true;
        if (route.route.endsWith('*')) {
            return pathname.startsWith(route.route.slice(0, -1));
        }
        return false;
    });

    if (!matchedRoute) {
        return new Response('Not Found', {status: 404});
    }

    // 检查缓存
    const cache = caches.default;
    const cacheKey = new Request(request.url, request);

    if (matchedRoute.cache_ttl > 0) {
        let cachedResponse = await cache.match(cacheKey);
        if (cachedResponse) {
            return cachedResponse;
        }
    }

    // 转发请求到源站
    const response = await fetch(request);

    // 缓存响应
    if (matchedRoute.cache_ttl > 0) {
        const cachedResponse = response.clone();
        cachedResponse.headers.set('Cache-Control', `public, max-age=${matchedRoute.cache_ttl}`);
        event.waitUntil(cache.put(cacheKey, cachedResponse));
    }

    return response;
}
