"""
应用配置 — src 入口（兼容层）

从 shared.config.settings 导入，保持旧路径兼容性。
新代码应直接从 shared.config.settings 导入。

 已废弃：此模块仅作为向后兼容的 re-export 层。
请迁移到: from shared.config.settings import settings
"""
from shared.config.settings import (  # noqa: F401
    settings, SECRET_KEY, JWT_SECRET_KEY, DB_ENGINE, DB_HOST, DB_PORT,
    DB_USER, DB_PASSWORD, DB_NAME, DB_TABLE_PREFIX, DB_POOL_SIZE,
    DB_POOL_OVERFLOW, DB_POOL_TIMEOUT, DB_POOL_RECYCLE, DOMAIN, TITLE,
    DESCRIPTION, KEYWORDS, TIME_ZONE, ENVIRONMENT, DEBUG, JWT_EXPIRATION_DELTA,
    REFRESH_TOKEN_EXPIRATION_DELTA, JWT_ALGORITHM, WORKERS, DISABLED_MODULES,
    REDIS_HOST, REDIS_PORT, REDIS_DB, REDIS_PASSWORD, REDIS_MAX_CONNECTIONS,
    CACHE_TTL_DEFAULT, CACHE_TTL_ARTICLES, CACHE_TTL_USERS, MAIL_SERVER,
    MAIL_PORT, MAIL_USE_TLS, MAIL_USERNAME, MAIL_PASSWORD, MAIL_FROM,
    MAIL_FROM_NAME, UPLOAD_LIMIT, USER_FREE_STORAGE_LIMIT, FRONTEND_PORT,
    BACKEND_PORT,
)
from shared.config.settings import _get_worker_info  # noqa: F401
